//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingCurator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prj666_191a03Entities : DbContext
    {
        public prj666_191a03Entities()
            : base("name=prj666_191a03Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALLERGY> ALLERGies { get; set; }
        public virtual DbSet<BMK> BMKs { get; set; }
        public virtual DbSet<DIET> DIETS { get; set; }
        public virtual DbSet<INGRED> INGREDs { get; set; }
        public virtual DbSet<RECIPE> RECIPES { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<WARN> WARNs { get; set; }
    }
}
