//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingCurator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRED
    {
        public int ingred_ID { get; set; }
        public string ingred_Name { get; set; }
        public int dietType { get; set; }
        public Nullable<int> allergenType { get; set; }
        public string measurement { get; set; }
    }
}
