//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingCurator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE
    {
        public RECIPE() {
            INGREDs = new HashSet<INGRED>();
        }

        public int recipe_ID { get; set; }
        public string title { get; set; }
        public int rating { get; set; }
        public string instructions { get; set; }
        public System.DateTime lastUpdated { get; set; }
        public string author { get; set; }
        public bool verified { get; set; }
        public Nullable<int> source_ID { get; set; }
        public string source_Link { get; set; }
        public string country { get; set; }
        public string mealTimeType { get; set; }

        public virtual ICollection<INGRED> INGREDs { get; set; }
    }
}
