//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingCurator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIPE_USERS
    {
        public int recipe_ID { get; set; }
        public int user_ID { get; set; }
        public Nullable<int> voting { get; set; }
        public Nullable<bool> reported { get; set; }
        public Nullable<bool> bookmarked { get; set; }
    }
}
