//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingCurator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int user_ID { get; set; }
        public string userName { get; set; }
        public bool acceptWaiver { get; set; }
        public bool banUser { get; set; }
        public Nullable<int> admin_ID { get; set; }
        public string userEmail { get; set; }
        public bool email_Verified { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string GUID { get; set; }
    }
}
