//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookingCurator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DIETS
    {
        public int user_Id { get; set; }
        public int diet_Id { get; set; }
    }
}
